/* Generated by re2c 1.3 on Wed Aug 10 19:29:11 2022 */
#line 1 "string_ops_schema.template"
#include "string_ops.h"
#include "mem_ops.h"

#define array_elements(array) (sizeof(array) / sizeof *(array))

// filter text of form input
// TODO fix it 
char *filter_text_form(char *text_module)
{

	char newline[]={' ',' ','\n'};
	char *clean_text=replace(text_module,"\\n",newline);
	char *clean_text2=replace(clean_text," \\t","  ");

	char *ret=rm_extra_slash(clean_text2);
	//char *ret2=rm_extra_slash(ret);

	//XFREE(clean_text2);
	//XFREE(clean_text);

	return ret;
}





char *rm_extra_slash(char *str)
{
        char *out = str, *put = str;
	short i=0;

        while(*str != '\0')
        {
                if(*str == '\\')
			i++;

		if(i==2)
			i=0;
		else
                	*put=*str,put++;
	
		str++;
	        	
        }

        *put = '\0';

        return out;
}




char *deadspace(char *str)
{
        char *out = str, *put = str;

        for(; *str != '\0'; ++str)
        {
                if(*str != ' ' || *str != '_' || *str != '\n' || *str != '\r')
                        *put++ = *str;
        }

        *put = '\0';

        return out;
}


char  *ClearStr(char* charBuffer,int num) 
{
	char *tmp=(charBuffer + num);
	tmp[strlen(tmp)-1]='\0';

	return tmp;
}

// DFA to parse egg module
int parse_eggs(char** p, char** lex)
{
      char* marker;

    for (;;) {
    *lex = *p;
    
#line 90 "string_ops.c"
	{
		char yych;
		unsigned int yyaccept = 0;
		static const unsigned char yybm[] = {
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			156,  60,  60,  56,  60,  60,  60,  60, 
			 60,  68,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  20,  60,  60,  60,   0,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
			 60,  60,  60,  60,  60,  60,  60,  60, 
		};
		yych = (char)**p;
		if (yych <= 0x00000000) goto yy2;
		if (yych == ':') goto yy6;
		goto yy4;
yy2:
		++*p;
#line 98 "string_ops_schema.template"
		{ return END; }
#line 136 "string_ops.c"
yy4:
		++*p;
yy5:
#line 99 "string_ops_schema.template"
		{ continue; }
#line 142 "string_ops.c"
yy6:
		yyaccept = 0;
		yych = (char)*(marker = ++*p);
		if (yych != ':') goto yy5;
		yych = (char)*++*p;
		if (yych <= 'T') {
			if (yych <= 'M') {
				if (yych == 'D') goto yy9;
				if (yych >= 'M') goto yy10;
			} else {
				if (yych == 'R') goto yy11;
				if (yych >= 'T') goto yy12;
			}
		} else {
			if (yych <= 'm') {
				if (yych == 'd') goto yy9;
				if (yych >= 'm') goto yy10;
			} else {
				if (yych <= 'r') {
					if (yych >= 'r') goto yy11;
				} else {
					if (yych == 't') goto yy12;
				}
			}
		}
yy8:
		*p = marker;
		if (yyaccept == 0) {
			goto yy5;
		} else {
			goto yy77;
		}
yy9:
		yych = (char)*++*p;
		if (yych == 'E') goto yy13;
		if (yych == 'e') goto yy13;
		goto yy8;
yy10:
		yych = (char)*++*p;
		if (yych == 'A') goto yy14;
		if (yych == 'a') goto yy14;
		goto yy8;
yy11:
		yych = (char)*++*p;
		if (yych == 'E') goto yy15;
		if (yych == 'e') goto yy15;
		goto yy8;
yy12:
		yych = (char)*++*p;
		if (yych == 'I') goto yy16;
		if (yych == 'i') goto yy16;
		goto yy8;
yy13:
		yych = (char)*++*p;
		if (yych == 'S') goto yy17;
		if (yych == 's') goto yy17;
		goto yy8;
yy14:
		yych = (char)*++*p;
		if (yych == 'T') goto yy18;
		if (yych == 't') goto yy18;
		goto yy8;
yy15:
		yych = (char)*++*p;
		if (yych <= 'L') {
			if (yych == 'F') goto yy19;
			if (yych <= 'K') goto yy8;
			goto yy20;
		} else {
			if (yych <= 'f') {
				if (yych <= 'e') goto yy8;
				goto yy19;
			} else {
				if (yych == 'l') goto yy20;
				goto yy8;
			}
		}
yy16:
		yych = (char)*++*p;
		if (yych == 'T') goto yy21;
		if (yych == 't') goto yy21;
		goto yy8;
yy17:
		yych = (char)*++*p;
		if (yych == 'C') goto yy22;
		if (yych == 'c') goto yy22;
		goto yy8;
yy18:
		yych = (char)*++*p;
		if (yych == 'C') goto yy23;
		if (yych == 'c') goto yy23;
		goto yy8;
yy19:
		yych = (char)*++*p;
		if (yych == 'E') goto yy24;
		if (yych == 'e') goto yy24;
		goto yy8;
yy20:
		yych = (char)*++*p;
		if (yych == 'E') goto yy25;
		if (yych == 'e') goto yy25;
		goto yy8;
yy21:
		yych = (char)*++*p;
		if (yych == 'L') goto yy26;
		if (yych == 'l') goto yy26;
		goto yy8;
yy22:
		yych = (char)*++*p;
		if (yych == 'R') goto yy27;
		if (yych == 'r') goto yy27;
		goto yy8;
yy23:
		yych = (char)*++*p;
		if (yych == 'H') goto yy28;
		if (yych == 'h') goto yy28;
		goto yy8;
yy24:
		yych = (char)*++*p;
		if (yych == 'R') goto yy29;
		if (yych == 'r') goto yy29;
		goto yy8;
yy25:
		yych = (char)*++*p;
		if (yych == 'V') goto yy30;
		if (yych == 'v') goto yy30;
		goto yy8;
yy26:
		yych = (char)*++*p;
		if (yych == 'E') goto yy31;
		if (yych == 'e') goto yy31;
		goto yy8;
yy27:
		yych = (char)*++*p;
		if (yych == 'I') goto yy32;
		if (yych == 'i') goto yy32;
		goto yy8;
yy28:
		yych = (char)*++*p;
		if (yych == ':') goto yy33;
		goto yy8;
yy29:
		yych = (char)*++*p;
		if (yych == 'E') goto yy34;
		if (yych == 'e') goto yy34;
		goto yy8;
yy30:
		yych = (char)*++*p;
		if (yych == 'A') goto yy35;
		if (yych == 'a') goto yy35;
		goto yy8;
yy31:
		yych = (char)*++*p;
		if (yych == ':') goto yy36;
		goto yy8;
yy32:
		yych = (char)*++*p;
		if (yych == 'P') goto yy37;
		if (yych == 'p') goto yy37;
		goto yy8;
yy33:
		yych = (char)*++*p;
		if (yych == ':') goto yy38;
		goto yy8;
yy34:
		yych = (char)*++*p;
		if (yych == 'N') goto yy39;
		if (yych == 'n') goto yy39;
		goto yy8;
yy35:
		yych = (char)*++*p;
		if (yych == 'N') goto yy40;
		if (yych == 'n') goto yy40;
		goto yy8;
yy36:
		yych = (char)*++*p;
		if (yych == ':') goto yy41;
		goto yy8;
yy37:
		yych = (char)*++*p;
		if (yych == 'T') goto yy42;
		if (yych == 't') goto yy42;
		goto yy8;
yy38:
		yych = (char)*++*p;
		if (yych == '#') goto yy43;
		goto yy8;
yy39:
		yych = (char)*++*p;
		if (yych == 'C') goto yy44;
		if (yych == 'c') goto yy44;
		goto yy8;
yy40:
		yych = (char)*++*p;
		if (yych == 'C') goto yy45;
		if (yych == 'c') goto yy45;
		goto yy8;
yy41:
		yych = (char)*++*p;
		if (yych == '(') goto yy46;
		goto yy8;
yy42:
		yych = (char)*++*p;
		if (yych == 'I') goto yy47;
		if (yych == 'i') goto yy47;
		goto yy8;
yy43:
		yych = (char)*++*p;
		if (yych == '#') goto yy8;
		goto yy49;
yy44:
		yych = (char)*++*p;
		if (yych == 'E') goto yy50;
		if (yych == 'e') goto yy50;
		goto yy8;
yy45:
		yych = (char)*++*p;
		if (yych == 'E') goto yy51;
		if (yych == 'e') goto yy51;
		goto yy8;
yy46:
		yych = (char)*++*p;
		if (yych == ')') goto yy8;
		if (yych == ':') goto yy8;
		goto yy53;
yy47:
		yych = (char)*++*p;
		if (yych == 'O') goto yy54;
		if (yych == 'o') goto yy54;
		goto yy8;
yy48:
		yych = (char)*++*p;
yy49:
		if (yych & ~0xFF) {
			goto yy48;
		} else if (yybm[0+yych] & 4) {
			goto yy48;
		}
		if (yych <= '#') goto yy55;
		goto yy8;
yy50:
		yych = (char)*++*p;
		if (yych == ':') goto yy57;
		goto yy8;
yy51:
		yych = (char)*++*p;
		if (yych == ':') goto yy58;
		goto yy8;
yy52:
		yych = (char)*++*p;
yy53:
		if (yych & ~0xFF) {
			goto yy52;
		} else if (yybm[0+yych] & 8) {
			goto yy52;
		}
		if (yych <= ':') goto yy59;
		goto yy8;
yy54:
		yych = (char)*++*p;
		if (yych == 'N') goto yy61;
		if (yych == 'n') goto yy61;
		goto yy8;
yy55:
		++*p;
#line 97 "string_ops_schema.template"
		{ return MATCH; }
#line 410 "string_ops.c"
yy57:
		yych = (char)*++*p;
		if (yych == ':') goto yy62;
		goto yy8;
yy58:
		yych = (char)*++*p;
		if (yych == ':') goto yy63;
		goto yy8;
yy59:
		++*p;
#line 93 "string_ops_schema.template"
		{ return TITLE; }
#line 423 "string_ops.c"
yy61:
		yych = (char)*++*p;
		if (yych == ':') goto yy64;
		goto yy8;
yy62:
		yych = (char)*++*p;
		if (yych == '(') goto yy65;
		goto yy8;
yy63:
		yych = (char)*++*p;
		if (yych == '(') goto yy66;
		goto yy8;
yy64:
		yych = (char)*++*p;
		if (yych == ':') goto yy67;
		goto yy8;
yy65:
		yych = (char)*++*p;
		if (yych == ')') goto yy8;
		goto yy69;
yy66:
		yych = (char)*++*p;
		if (yych <= '9') {
			if (yych == ')') goto yy8;
			goto yy70;
		} else {
			if (yych <= ':') goto yy8;
			if (yych == '>') goto yy8;
			goto yy70;
		}
yy67:
		yych = (char)*++*p;
		if (yych == '(') goto yy72;
		goto yy8;
yy68:
		yych = (char)*++*p;
yy69:
		if (yych & ~0xFF) {
			goto yy68;
		} else if (yybm[0+yych] & 16) {
			goto yy68;
		}
		if (yych <= ')') goto yy73;
		goto yy8;
yy70:
		yych = (char)*++*p;
		if (yych & ~0xFF) {
			goto yy70;
		} else if (yybm[0+yych] & 32) {
			goto yy70;
		}
		if (yych <= ' ') goto yy75;
		if (yych <= ':') goto yy78;
		goto yy8;
yy72:
		yych = (char)*++*p;
		if (yych == ')') goto yy8;
		if (yych == ':') goto yy8;
		goto yy80;
yy73:
		yych = (char)*++*p;
		if (yych & ~0xFF) {
			goto yy8;
		} else if (yybm[0+yych] & 64) {
			goto yy73;
		}
		if (yych == ':') goto yy81;
		goto yy8;
yy75:
		yyaccept = 1;
		yych = (char)*(marker = ++*p);
		if (yych & ~0xFF) {
			goto yy70;
		} else if (yybm[0+yych] & 32) {
			goto yy70;
		}
		if (yych <= ' ') goto yy75;
		if (yych <= ':') goto yy78;
yy77:
#line 95 "string_ops_schema.template"
		{ return RELEVANCE; }
#line 505 "string_ops.c"
yy78:
		++*p;
		goto yy77;
yy79:
		yych = (char)*++*p;
yy80:
		if (yych <= '9') {
			if (yych == ')') goto yy82;
			goto yy79;
		} else {
			if (yych <= ':') goto yy82;
			if (yych == '>') goto yy8;
			goto yy79;
		}
yy81:
		yych = (char)*++*p;
		if (yych == ':') goto yy84;
		goto yy8;
yy82:
		++*p;
#line 94 "string_ops_schema.template"
		{ return DESCRIPTION; }
#line 528 "string_ops.c"
yy84:
		++*p;
#line 96 "string_ops_schema.template"
		{ return REFERENCE; }
#line 533 "string_ops.c"
	}
#line 100 "string_ops_schema.template"

    }
}


bool match_test(const char *string,size_t string_len,const char *expression)
{
	const char *err;
	int errofs = 0, offset = 0;
	int ovector[1024];

	pcre *re = pcre_compile(expression, 0, &err, &errofs, NULL);

	if (re == NULL) 
	{
		DEBUG(" REGEX compilation failed : %s\n",expression);
		return false;
	}
	const int rc = pcre_exec(re, NULL, string, string_len, offset, 0, ovector, 1024);
	pcre_free(re);

	return (rc > 0)?true:false;
}


// DFA for parser
int parse_viewcode(char** p, char** lex)
{
    char* marker;

    for (;;) {
    *lex = *p;
    

	{
		char yych;

		yych = (char)**p;
		switch (yych) {
		case 0x00:	goto yy5;
		case 'l':	goto yy4;
		case 'p':	goto yy2;
		default:	goto yy7;
		}
yy2:
		yych = (char)*(marker = ++*p);
		switch (yych) {
		case 'a':	goto yy25;
		default:	goto yy3;
		}
yy3:

		{ continue; }

yy4:
		yych = (char)*(marker = ++*p);
		switch (yych) {
		case 'a':	goto yy10;
		case 'i':	goto yy8;
		default:	goto yy3;
		}
yy5:
		++*p;

		{ return END; }

yy7:
		yych = (char)*++*p;
		goto yy3;
yy8:
		yych = (char)*++*p;
		switch (yych) {
		case 'n':	goto yy18;
		default:	goto yy9;
		}
yy9:
		*p = marker;
		goto yy3;
yy10:
		yych = (char)*++*p;
		switch (yych) {
		case 'n':	goto yy11;
		default:	goto yy9;
		}
yy11:
		yych = (char)*++*p;
		switch (yych) {
		case 'g':	goto yy12;
		default:	goto yy9;
		}
yy12:
		yych = (char)*++*p;
		switch (yych) {
		case '=':	goto yy13;
		default:	goto yy9;
		}
yy13:
		yych = (char)*++*p;
		switch (yych) {
		case '&':	goto yy9;
		default:	goto yy14;
		}
yy14:
		++*p;
		yych = (char)**p;
		switch (yych) {
		case '&':	goto yy16;
		default:	goto yy14;
		}
yy16:
		++*p;

		{ return LANG; }

yy18:
		yych = (char)*++*p;
		switch (yych) {
		case 'e':	goto yy19;
		default:	goto yy9;
		}
yy19:
		yych = (char)*++*p;
		switch (yych) {
		case 's':	goto yy20;
		default:	goto yy9;
		}
yy20:
		yych = (char)*++*p;
		switch (yych) {
		case '=':	goto yy21;
		default:	goto yy9;
		}
yy21:
		yych = (char)*++*p;
		switch (yych) {
		case '\n':	goto yy9;
		default:	goto yy22;
		}
yy22:
		++*p;
		yych = (char)**p;
		switch (yych) {
		case '\n':	goto yy24;
		default:	goto yy22;
		}
yy24:

		{ return LINES; }

yy25:
		yych = (char)*++*p;
		switch (yych) {
		case 't':	goto yy26;
		default:	goto yy9;
		}
yy26:
		yych = (char)*++*p;
		switch (yych) {
		case 'h':	goto yy27;
		default:	goto yy9;
		}
yy27:
		yych = (char)*++*p;
		switch (yych) {
		case '=':	goto yy28;
		default:	goto yy9;
		}
yy28:
		yych = (char)*++*p;
		switch (yych) {
		case '&':	goto yy9;
		default:	goto yy29;
		}
yy29:
		++*p;
		yych = (char)**p;
		switch (yych) {
		case '&':	goto yy31;
		default:	goto yy29;
		}
yy31:
		++*p;

		{ return PATH; }

	}


    }
}


char *get_extension(char *extension)
{
	char *language=xmalloc(16);
	size_t extension_size=strlen(extension);

	memset(language,0,15);

	if(strnstr(extension,".c",extension_size)||strnstr(extension,"cpp",extension_size))
	{
		strlcat(language,"cpp",16);
		goto etx_end;
	}

	if(strnstr(extension,"java",extension_size)||strnstr(extension,"jad",extension_size)||strnstr(extension,"class",extension_size))
	{	
		strlcat(language,"java",16);
		goto etx_end;
	}

	if(strnstr(extension,".php",extension_size))
	{
		strlcat(language,"php",16);
		goto etx_end;
	}

	if(strnstr(extension,".rb",extension_size))
	{
		strlcat(language,"ruby",16);
		goto etx_end;
	}

	if(strnstr(extension,".js",extension_size)||strnstr(extension,"html",extension_size))
	{
		strlcat(language,"javascript",16);
		goto etx_end;
	}

	if(strnstr(extension,"asp",extension_size)||strnstr(language,".cs",extension_size))
	{
		strlcat(language,"bash",16);
		goto etx_end;
	}
	
	if(strnstr(extension,".py",extension_size))
	{
		strlcat(language,"python",16);
		goto etx_end;
	}

	if(strnstr(extension,".go",extension_size)||strnstr(extension,"golang",extension_size))
	{
		strlcat(language,"go",16);
		goto etx_end;
	}

	if(strnstr(extension,".kt",extension_size)||strnstr(extension,".kotlin",extension_size))
	{
		strlcat(language,"kotlin",16);
		goto etx_end;
	}

	if(strnstr(extension,".swift",extension_size))
	{
		strlcat(language,"swift",16);
		goto etx_end;
	}

	if(strnstr(extension,".cs",extension_size))
	{
		strlcat(language,"csharp",16);
		goto etx_end;
	}

	etx_end:
	return language;
}


char *get_relevance_icon(char *relevance)
{
	char *icon_alert=xmalloc(sizeof(char)*16);
	size_t relevance_size=strlen(relevance);

	memset(icon_alert,0,15);

	if(strnstr(relevance,"High",relevance_size)||strnstr(relevance,"high",relevance_size))
	{
		strlcat(icon_alert,"Heat.png",16);
		goto icon_end;
	}

	if(strnstr(relevance,"Low",relevance_size)||strnstr(relevance,"low",relevance_size))
	{
		strlcat(icon_alert,"Snow.png",16);
		goto icon_end;
	}

	if(strnstr(relevance,"Medium",relevance_size)||strnstr(relevance,"medium",relevance_size))
	{
		strlcat(icon_alert,"Shuriken.png",16);
		goto icon_end;
	}

	icon_end:
	return icon_alert;
}

int ishex(int x)
{
	return	(x >= '0' && x <= '9')	||
		(x >= 'a' && x <= 'f')	||
		(x >= 'A' && x <= 'F');
}
 
int URLdecode(const char *s, char *dec)
{
	char *o;
	const char *end = s + strlen(s);
	int c;
 
	for (o = dec; s <= end; o++) 
	{
		c = *s++;

		if (c == '+') 
			c = ' ';
		else if (c == '%' && (	!ishex(*s++)	||
					!ishex(*s++)	||
					!sscanf(s - 2, "%2x", &c)))
			return -1;
 
		if (dec) 
			*o = c;
	}
 
	return o - dec;
}

// audit thuis, change strcpy to strlcpy...
char *replace(const char *in, const char *pattern, const char *by)
{
    size_t outsize = strlen(in) + 1;
    char *res = xmallocarray(outsize,sizeof(char));
    size_t resoffset = 0;
    char *needle;

    while ((needle = strstr(in, pattern))) 
    {
        memcpy(res + resoffset, in, needle - in);
        resoffset += needle - in;
        in = needle + strlen(pattern);
        outsize = outsize - strlen(pattern) + strlen(by);
        res = xreallocarray(res, outsize,sizeof(char));
        memcpy(res + resoffset, by, strlen(by));
        resoffset += strlen(by);
    }

    strlcpy(res + resoffset, in,outsize);

    return res;
}
